AllCops:
  TargetRubyVersion: 2.5.1

Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*_spec.rb'
