AllCops:
  TargetRubyVersion: 2.5.5

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
