env:
  global:
  - CC_TEST_REPORTER_ID=8fc19590bd3eca85d2be16784dc5312c06236b25637374a490f191575eeef82e

language: ruby
rvm:
- 2.5.5

before_install:
- openssl aes-256-cbc -K $encrypted_e68bdaa77bba_key -iv $encrypted_e68bdaa77bba_iv
  -in .travis.enc -out spec/spec_helper.rb -d

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- bundle exec rspec

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
